# Generated by Django 5.1.4 on 2024-12-20 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='file',
            field=models.FileField(upload_to='podcast_uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['flac', 'ogg', 'mp3', 'wav'])], verbose_name='Podcast File'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='thumbnail',
            field=models.ImageField(upload_to='podcast_thumbnails', verbose_name='Podcast Thumbnail'),
        ),
    ]
