# Generated by Django 5.1.4 on 2025-01-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_podcast_file_alter_podcast_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='m3u8_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='M3U8 URL'),
        ),
    ]
