# Generated by Django 5.1.4 on 2025-01-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_podcast_m3u8_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.CharField(max_length=1000, verbose_name='email')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('message', models.CharField(max_length=10000, verbose_name='message')),
            ],
        ),
    ]
