# Generated by Django 5.1.4 on 2025-01-10 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=10000, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Phone number must be between 10 and 15 digits.')], verbose_name='phone'),
        ),
    ]
