# Generated by Django 5.1.4 on 2025-03-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_podcast_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='category',
        ),
        migrations.AddField(
            model_name='podcast',
            name='category',
            field=models.ManyToManyField(blank=True, to='core.category', verbose_name='Category'),
        ),
    ]
