# Generated by Django 5.1.4 on 2025-03-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_podcast_category_podcast_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='category',
            field=models.ManyToManyField(blank=True, to='core.category', verbose_name='Categories'),
        ),
    ]
