# Generated by Django 5.1.4 on 2025-03-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_podcast_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='category',
            new_name='categories',
        ),
    ]
